# Use a imagem base do PostgreSQL
FROM postgres:latest

# Defina variáveis de ambiente para configuração do banco de dados
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=123456
ENV POSTGRES_DB=find_my_pet

# Exponha a porta padrão do PostgreSQL
EXPOSE 5432

# Copie o arquivo SQL para inicialização do banco de dados
COPY ./init/ /docker-entrypoint-initdb.d/